name = "PLEXOSUtilsx"
uuid = "d19dde98-b8c4-4cd6-bed4-e0b4b8aa10a8"
authors = ["Gord Stephen <gord.stephen@nrel.gov>"]
version = "0.1.10"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
InfoZIPx = "85c6e0d9-4115-4be7-bf85-ff2b3d30e22f"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
